on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - develop 
      - staging
  issue_comment:
jobs:
  pr-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PR-Agent
        run: pip install pr-agent

      - name: Run PR-Agent Review with Debugging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pr-agent review --repo-url ${{ github.repository }} \
                          --pr-number ${{ github.event.pull_request.number }} \
                          --verbose || echo "PR-Agent failed. Retrying..."
          sleep 10
          pr-agent review --repo-url ${{ github.repository }} \
                          --pr-number ${{ github.event.pull_request.number }} \
                          --verbose
















  # pr_agent_job:
  #   if: ${{ github.event.sender.type != 'Bot' }}
  #   runs-on: ubuntu-latest
  #   permissions:
  #     issues: write
  #     pull-requests: write
  #     contents: write
  #   name: Run pr agent on every pull request, respond to user comments
  #   steps:
  #     - name: PR Agent action step
  #       id: pragent
  #       uses: docker://codiumai/pr-agent:0.25-github_action
  #       env:
  #         OPENAI_KEY: ${{ secrets.OPENAI_KEY }} # Make sure to add your OpenAI key to your repo secrets
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Make sure to add your GitHub token to your repo secrets
  #         github_action_config.auto_review: "true" # enable\disable auto review
  #         github_action_config.auto_describe: "true" # enable\disable auto describe
